import type {
  ArchitectureDomain,
  ArchitectureEdge,
  ArchitectureGraph,
  ArchitectureNode,
  Journey,
  JourneyId,
} from './architecture-schema';
import { architectureEdgeDetail } from './relationship-content';
export {
  ARCHITECTURE_DOMAIN_IDS,
  ARCHITECTURE_LOGO_IDS,
  ARCHITECTURE_STATUS_META,
  ARCHITECTURE_VISUAL_KINDS,
} from './architecture-schema';
export type {
  ArchitectureDomain,
  ArchitectureDomainId,
  ArchitectureEdge,
  ArchitectureGraph,
  ArchitectureLogoId,
  ArchitectureNode,
  ArchitectureStatus,
  ArchitectureStatusMeta,
  ArchitectureVisualKind,
  Journey,
  JourneyId,
} from './architecture-schema';

const cloudDocs = 'https://github.com/A3S-Lab/Cloud/blob/main';

export const ARCHITECTURE_DOMAINS: readonly ArchitectureDomain[] = [
  {
    id: 'experience',
    label: 'Experience & Sources',
    shortLabel: '01 · Intent',
    description: 'People, automation, source providers, and inference intent',
    center: [0, 14],
    size: [32, 3.2],
    color: '#72b7ff',
  },
  {
    id: 'access',
    label: 'Public Access & Delivery',
    shortLabel: '02 · Gateway boundary',
    description: 'Same-origin SPA/API routing, TLS termination, and workload ingress',
    center: [0, 10.3],
    size: [12, 2.2],
    color: '#5dd6ff',
  },
  {
    id: 'control',
    label: 'Cloud Control Domains',
    shortLabel: '03 · Control plane',
    description: 'Tenant-scoped authority, product semantics, desired state, reconciliation, and policy',
    center: [0, 5.2],
    size: [32, 8.2],
    color: '#b8f36b',
  },
  {
    id: 'coordination',
    label: 'Platform Middleware & State',
    shortLabel: '04 · Middleware',
    description: 'One SQL authority, one Flow history, committed integration facts, and governed storage',
    center: [0, -0.1],
    size: [32, 3],
    color: '#d7b6ff',
  },
  {
    id: 'data-plane',
    label: 'Managed Node Plane',
    shortLabel: '05 · Node execution',
    description: 'Outbound node control and provider-neutral Runtime execution',
    center: [0, -3.7],
    size: [14, 2.6],
    color: '#71d5c3',
  },
  {
    id: 'ecosystem',
    label: 'Provider & Workload Layer',
    shortLabel: '06 · Providers',
    description: 'Sole A3S Box execution/build path and converged Cloud workload units',
    center: [0, -7.2],
    size: [32, 2.6],
    color: '#f3c86b',
  },
  {
    id: 'infrastructure',
    label: 'Infrastructure & Hardware',
    shortLabel: '07 · Physical resources',
    description: 'OCI distribution plus the CPU and GPU rack clusters that supply execution',
    center: [0, -10.9],
    size: [32, 2.8],
    color: '#ff9f72',
  },
] as const;

export const ARCHITECTURE_NODES: readonly ArchitectureNode[] = [
  {
    id: 'clients',
    label: 'Clients & SDKs',
    eyebrow: 'Request origin',
    domain: 'experience',
    position: [-13.35, 0.28, 14],
    visualKind: 'client-terminal',
    logoId: 'clients',
    status: 'external',
    gate: 'External',
    summary: 'Browsers, operators, automation, and OpenAI-compatible clients originate intent and traffic.',
    owns: ['User intent', 'API requests', 'Traffic payloads'],
    boundary: 'Clients never receive provider credentials or direct access to Cloud durable state.',
    docsUrl: `${cloudDocs}/docs/architecture.md`,
  },
  {
    id: 'web',
    label: 'Web Console',
    eyebrow: 'Management surface',
    domain: 'experience',
    position: [-8, 0.28, 14],
    visualKind: 'web-console',
    logoId: 'a3s-web',
    status: 'verified',
    gate: 'F0',
    summary: 'The same-origin management SPA consumes authoritative command, query, operation, and log APIs.',
    owns: ['Operator experience', 'Status projections', 'Safe command initiation'],
    boundary: 'The console owns no business rule and cannot bypass tenant or idempotency guards.',
    docsUrl: `${cloudDocs}/docs/architecture.md#41-management-web-delivery`,
  },
  {
    id: 'a3s-box',
    label: 'A3S Box (Local)',
    eyebrow: 'Local OCI workload host',
    domain: 'experience',
    position: [8, 0.28, 14],
    visualKind: 'box-runtime',
    logoId: 'a3s-box',
    status: 'verified',
    gate: 'Local host',
    summary:
      'A local A3S Box hosts isolated agent products and tools; A3S Code is one workload installed inside it.',
    owns: ['OCI workload lifecycle', 'Workspace and filesystem isolation', 'MicroVM or sandbox execution'],
    boundary:
      'Box owns execution and isolation, while its hosted products own their workflows and Cloud owns tenant orchestration.',
    docsUrl: 'https://github.com/A3S-Lab/Box',
  },
  {
    id: 'code-tui',
    label: 'A3S Code TUI',
    eyebrow: 'Developer workspace',
    domain: 'experience',
    position: [13.35, 0.28, 14],
    visualKind: 'code-terminal',
    logoId: 'a3s-code',
    status: 'planned',
    gate: 'C0',
    summary:
      'Installed inside a local A3S Box, A3S Code uses its TUI, CLI, and management MCP tools to operate Cloud.',
    owns: ['Developer workflow', 'TUI interactions', 'Scoped management tools'],
    boundary:
      'A3S Code is one Box-hosted workload; it never receives provider credentials or introduces a second orchestration path.',
    docsUrl: `${cloudDocs}/docs/development-plan.md`,
  },
  {
    id: 'github',
    label: 'GitHub Source',
    eyebrow: 'External provider',
    domain: 'experience',
    position: [-2.7, 0.28, 14],
    visualKind: 'source-repository',
    logoId: 'github',
    status: 'in-progress',
    gate: 'G0',
    summary: 'Signed webhooks and short-lived GitHub App credentials resolve one exact source revision.',
    owns: ['Repository events', 'Installation authority', 'Immutable Git objects'],
    boundary: 'Mutable refs and credentials never become Cloud source truth.',
    docsUrl: `${cloudDocs}/docs/domain-model.md#33-external-sources`,
  },
  {
    id: 'inference',
    label: 'Cloud Inference (I0)',
    eyebrow: 'Planned bounded context',
    domain: 'control',
    position: [0, 0.28, 5.25],
    visualKind: 'inference-control',
    logoId: 'inference',
    status: 'planned',
    gate: 'I0',
    summary:
      'The planned Cloud bounded context owns model, Provider, typed protocol, route, and usage intent and compiles execution into generic Workloads, Fleet claims, and Edge policy.',
    owns: ['Model and Provider catalog', 'Typed protocol and backend plans', 'Model routes and usage'],
    boundary:
      'Core and optional protocol profiles reuse one Identity, Secret, Inference, Edge/Gateway, and usage path; Cloud Inference is not another scheduler, proxy, key store, or physical backend.',
    docsUrl: `${cloudDocs}/docs/inference-plan.md`,
  },
  {
    id: 'workflow',
    label: 'Workflow & Ontology',
    eyebrow: 'Planned semantic authority',
    domain: 'control',
    position: [-10, 0.28, 9.1],
    visualKind: 'workflow-orchestrator',
    logoId: 'workflow',
    status: 'planned',
    gate: 'W0',
    summary:
      'Owns versioned business ontologies, goals, deterministic plan revisions, Workflow runs, and human decisions.',
    owns: ['Ontology and Workflow revisions', 'Goal and deterministic plan', 'Workflow run semantics'],
    boundary:
      'PostgreSQL through A3S ORM is authoritative; Workflow compiles durable work to Operations and A3S Flow instead of adding an engine, scheduler, or Runtime.',
    docsUrl: `${cloudDocs}/docs/workflow-evolution-plan.md`,
  },
  {
    id: 'agents',
    label: 'Agent Execution',
    eyebrow: 'Provider-neutral Cloud lifecycle',
    domain: 'control',
    position: [5, 0.28, 9.1],
    visualKind: 'workload-cluster',
    logoId: 'agents',
    status: 'in-progress',
    gate: 'A0 · A1',
    summary:
      'Owns one Agent execution lifecycle and semantic contract across heterogeneous Harness providers; A3S Code is native.',
    owns: [
      'Conversation and AgentExecution',
      'Invocation profile and semantic events',
      'Approval, recovery, and lineage',
    ],
    boundary:
      'PostgreSQL holds provider-neutral Cloud state; providers retain private details but cannot add a controller, scheduler, run store, node channel, or Runtime.',
    docsUrl: `${cloudDocs}/docs/workflow-evolution-plan.md`,
  },
  {
    id: 'evolution',
    label: 'Governed Evolution',
    eyebrow: 'Planned evidence authority',
    domain: 'control',
    position: [11, 0.28, 9.1],
    visualKind: 'artifact-factory',
    logoId: 'evolution',
    status: 'planned',
    gate: 'EV0',
    summary:
      'Owns authorized evidence datasets, evaluation suites, candidates, promotion decisions, and rollback evidence.',
    owns: ['Evidence dataset manifest', 'Evaluation and candidate revision', 'Promotion decision'],
    boundary:
      'PostgreSQL holds decisions and telemetry is evidence only; jobs reuse Flow and Workloads, while promotion uses owning-context rollout authority.',
    docsUrl: `${cloudDocs}/docs/workflow-evolution-plan.md`,
  },
  {
    id: 'api',
    label: 'A3S Boot API',
    eyebrow: 'Control-plane boundary',
    domain: 'control',
    position: [0, 0.28, 7.6],
    visualKind: 'control-tower',
    logoId: 'a3s-boot',
    status: 'verified',
    gate: 'F0',
    summary:
      'Authenticated HTTP boundaries establish tenant context and dispatch typed commands and queries.',
    owns: ['Transport validation', 'Tenant context', 'Response contracts'],
    boundary: 'Controllers remain thin; provider details and business rules stay behind application ports.',
    docsUrl: `${cloudDocs}/docs/architecture.md#2-system-shape`,
  },
  {
    id: 'identity',
    label: 'Identity',
    eyebrow: 'Bounded context',
    domain: 'control',
    position: [-12, 0.28, 5.25],
    visualKind: 'identity-vault',
    logoId: 'identity',
    status: 'verified',
    gate: 'F0',
    summary: 'Organizations, memberships, tokens, grants, and the tenant security boundary.',
    owns: ['Organization', 'Membership', 'API token'],
    boundary: 'Identity decides who may issue a command, not where a workload runs.',
    docsUrl: `${cloudDocs}/docs/domain-model.md#31-identity-and-access`,
  },
  {
    id: 'projects',
    label: 'Projects',
    eyebrow: 'Bounded context',
    domain: 'control',
    position: [-7, 0.28, 5.25],
    visualKind: 'project-blocks',
    logoId: 'projects',
    status: 'verified',
    gate: 'F0',
    summary: 'Projects and environments form the product and desired-state namespace hierarchy.',
    owns: ['Project', 'Environment', 'Attribution profile'],
    boundary: 'Environment deletion and other long work are durable operations, not hidden cascades.',
    docsUrl: `${cloudDocs}/docs/domain-model.md#32-projects`,
  },
  {
    id: 'sources',
    label: 'Sources',
    eyebrow: 'Bounded context',
    domain: 'control',
    position: [7, 0.28, 5.25],
    visualKind: 'source-branch',
    logoId: 'sources',
    status: 'in-progress',
    gate: 'G0',
    summary:
      'Provider authority and immutable external source revisions are accepted without durable credentials.',
    owns: ['GitHub connection', 'Subscription', 'External source revision'],
    boundary: 'Sources owns provider identity and revision truth, not builds or deployment.',
    docsUrl: `${cloudDocs}/docs/domain-model.md#33-external-sources`,
  },
  {
    id: 'artifacts',
    label: 'Artifacts',
    eyebrow: 'Bounded context',
    domain: 'control',
    position: [12, 0.28, 5.25],
    visualKind: 'artifact-factory',
    logoId: 'artifacts',
    status: 'in-progress',
    gate: 'G0',
    summary:
      'Isolated builds produce validated, signed, content-addressed OCI graphs and trusted retry caches.',
    owns: ['BuildRun', 'OCI descriptor', 'SBOM and provenance'],
    boundary: 'Every cache hit and publication is revalidated against immutable source and builder inputs.',
    docsUrl: `${cloudDocs}/docs/domain-model.md#35-artifacts`,
  },
  {
    id: 'workloads',
    label: 'Workloads',
    eyebrow: 'Bounded context',
    domain: 'control',
    position: [-9, 0.28, 2.85],
    visualKind: 'workload-cluster',
    logoId: 'workloads',
    status: 'historical',
    gate: 'D0 · E0',
    summary:
      'One deployment abstraction owns revisions, placement intent, rollout, health, stop, and rollback.',
    owns: ['Workload', 'Workload revision', 'Deployment'],
    boundary: 'Applications, Agents, MCP services, and inference all reuse this path.',
    docsUrl: `${cloudDocs}/docs/domain-model.md#37-workloads-and-deployments`,
  },
  {
    id: 'fleet',
    label: 'Fleet',
    eyebrow: 'Bounded context',
    domain: 'control',
    position: [-3, 0.28, 2.85],
    visualKind: 'fleet-radar',
    logoId: 'fleet',
    status: 'historical',
    gate: 'N0 · E0',
    summary: 'Node identity, capabilities, leases, observations, drain, and ordered log ingestion.',
    owns: ['Node', 'Command lease', 'Observation and log cursor'],
    boundary: 'Nodes connect outward and never receive PostgreSQL or NATS credentials.',
    docsUrl: `${cloudDocs}/docs/domain-model.md#36-fleet`,
  },
  {
    id: 'edge',
    label: 'Edge',
    eyebrow: 'Bounded context',
    domain: 'control',
    position: [3, 0.28, 2.85],
    visualKind: 'edge-router',
    logoId: 'edge',
    status: 'historical',
    gate: 'E0',
    summary: 'Domains, managed TLS, routes, complete Gateway snapshots, and exact acknowledgements.',
    owns: ['Domain claim', 'Route', 'Gateway snapshot'],
    boundary: 'Cloud owns complete policy; Gateway applies it atomically without inventing desired state.',
    docsUrl: `${cloudDocs}/docs/domain-model.md#39-edge`,
  },
  {
    id: 'operations',
    label: 'Operations',
    eyebrow: 'Bounded context',
    domain: 'control',
    position: [9, 0.28, 2.85],
    visualKind: 'operations-timeline',
    logoId: 'operations',
    status: 'verified',
    gate: 'F0',
    summary:
      'Durable operation projections expose long-running progress, cancellation, replay, and recovery.',
    owns: ['Operation record', 'Workflow identity', 'Timeline projection'],
    boundary:
      'A business commit and a Flow run converge idempotently across their crash gap; planned C0.3 security investigations remain read-only evidence projections.',
    docsUrl: `${cloudDocs}/docs/domain-model.md#310-operations`,
  },
  {
    id: 'postgres',
    label: 'PostgreSQL',
    eyebrow: 'Authoritative state',
    domain: 'coordination',
    position: [-12, 0.28, -0.1],
    visualKind: 'database',
    logoId: 'postgresql',
    status: 'verified',
    gate: 'F0',
    summary: 'The source of truth for aggregates, desired state, idempotency, outbox, and UI projections.',
    owns: ['Business state', 'Optimistic versions', 'Transactional outbox'],
    boundary: 'Provider observations become durable facts before they can advance desired state.',
    docsUrl: `${cloudDocs}/docs/architecture.md#5-data-and-consistency-ownership`,
  },
  {
    id: 'flow',
    label: 'A3S Flow',
    eyebrow: 'Operation history',
    domain: 'coordination',
    position: [-4, 0.28, -0.1],
    visualKind: 'workflow-orchestrator',
    logoId: 'a3s-flow',
    status: 'verified',
    gate: 'F0',
    summary: 'Coordinates long-lived, replay-safe deployment, build, rollback, and repair workflows.',
    owns: ['Workflow event history', 'Durable step state', 'Retry coordination'],
    boundary: 'Flow coordinates side effects; it does not replace aggregate invariants.',
    docsUrl: `${cloudDocs}/docs/architecture.md#5-data-and-consistency-ownership`,
  },
  {
    id: 'event',
    label: 'A3S Event',
    eyebrow: 'Committed facts',
    domain: 'coordination',
    position: [4, 0.28, -0.1],
    visualKind: 'event-bus',
    logoId: 'a3s-event',
    status: 'verified',
    gate: 'F0',
    summary: 'The outbox relay publishes integration facts only after the originating transaction commits.',
    owns: ['Integration events', 'Outbox relay', 'Redelivery'],
    boundary: 'Events distribute facts but never repair an invariant inside the same transaction.',
    docsUrl: `${cloudDocs}/docs/architecture.md#2-system-shape`,
  },
  {
    id: 'object-storage',
    label: 'Cloud Storage Plane',
    eyebrow: 'Immutable live · mutable planned',
    domain: 'coordination',
    position: [12, 0.28, -0.1],
    visualKind: 'object-storage',
    logoId: 'object-store',
    status: 'in-progress',
    gate: 'G0 + planned S0',
    summary:
      'Immutable log and Artifact bytes use one content-addressed client today; S0 extends the same plane with fenced distributed mutable storage.',
    owns: ['Verified immutable bytes', 'Fenced mutable volume handles', 'Retention lifecycle'],
    boundary:
      'PostgreSQL remains business authority; immutable objects and mutable volumes keep distinct semantics without separate storage control planes.',
    docsUrl: `${cloudDocs}/docs/architecture.md`,
  },
  {
    id: 'node-agent',
    label: 'Node Agent',
    eyebrow: 'Outbound control',
    domain: 'data-plane',
    position: [-3, 0.28, -3.7],
    visualKind: 'node-antenna',
    logoId: 'node-agent',
    status: 'historical',
    gate: 'N0 · E0',
    summary:
      'Outbound mTLS long polling applies leased commands and journals exact outcomes across restarts.',
    owns: ['Command journal', 'Artifact transport', 'Observed provider state'],
    boundary: 'The agent has node-local authority only for the exact leased command.',
    docsUrl: `${cloudDocs}/docs/architecture.md`,
  },
  {
    id: 'runtime',
    label: 'A3S Runtime',
    eyebrow: 'Provider-neutral execution',
    domain: 'data-plane',
    position: [3, 0.28, -3.7],
    visualKind: 'runtime-engine',
    logoId: 'a3s-runtime',
    status: 'historical',
    gate: 'R0',
    summary:
      'A common Task and Service contract with immutable specs, health, outputs, and idempotent recovery.',
    owns: ['RuntimeUnit', 'Task and Service lifecycle', 'Provider receipt'],
    boundary: 'Runtime contains no Cloud tenant, product asset, or inference scheduling semantics.',
    docsUrl: `${cloudDocs}/docs/architecture.md#3-universal-a3s-runtime-boundary`,
  },
  {
    id: 'gateway',
    label: 'A3S Gateway',
    eyebrow: 'Public same-origin boundary',
    domain: 'access',
    position: [0, 0.28, 10.3],
    visualKind: 'traffic-gateway',
    logoId: 'a3s-gateway',
    status: 'historical',
    gate: 'E0',
    summary:
      'Forms the live data plane of Unified Gateway, routing management requests to Cloud API and traffic to acknowledged workloads.',
    owns: ['Public transport and TLS', 'Same-origin API/SPA routing', 'Atomic workload route snapshots'],
    boundary:
      'Cloud API owns identity and desired policy; Gateway applies protocol and routing policy without scheduling, promotion, or business-state authority.',
    docsUrl: 'https://github.com/A3S-Lab/Gateway/blob/main/ROADMAP.md',
  },
  {
    id: 'box-provider',
    label: 'A3S Box Provider',
    eyebrow: 'Sole execution & build provider',
    domain: 'ecosystem',
    position: [-8, 0.28, -7.2],
    visualKind: 'box-workload-host',
    logoId: 'a3s-box-provider',
    status: 'in-progress',
    gate: 'BX0',
    summary:
      'The sole A3S Runtime driver executes Tasks, Services, and source builds in isolated MicroVMs or certified sandboxes.',
    owns: ['Box-backed Runtime units', 'Typed source builds', 'Provider health, output, and cleanup'],
    boundary:
      'A3S Box owns execution, build, and isolation mechanics; Runtime retains one lifecycle contract and Cloud retains desired state.',
    docsUrl: `${cloudDocs}/docs/architecture.md#34-provider-conformance`,
  },
  {
    id: 'power',
    label: 'A3S Power',
    eyebrow: 'TEE inference backend',
    domain: 'ecosystem',
    position: [0, 0.28, -7.2],
    visualKind: 'gpu-cluster',
    logoId: 'a3s-power',
    status: 'planned',
    gate: 'PW0 · I0',
    summary:
      'A privacy-preserving OpenAI-compatible inference backend that can run inside a Cloud-managed workload after provider conformance.',
    owns: [
      'Inference engine lifecycle',
      'TEE attestation and receipts',
      'Model integrity and content redaction',
    ],
    boundary:
      'Power never owns the Cloud model catalog, placement, accelerator claims, workload reconciliation, or Gateway route policy.',
    docsUrl: 'https://github.com/A3S-Lab/Power',
  },
  {
    id: 'workload-unit',
    label: 'Cloud Workload Units',
    eyebrow: 'Converged resources',
    domain: 'ecosystem',
    position: [8, 0.28, -7.2],
    visualKind: 'healthy-runtime',
    logoId: 'runtime-unit',
    status: 'historical',
    gate: 'D0 · E0',
    summary:
      'Digest-pinned revisions become observable provider resources carried through the sole A3S Box execution path.',
    owns: ['Provider resource', 'Health evidence', 'Ordered logs'],
    boundary: 'A unit becomes active only after exact health and routing acknowledgement gates pass.',
    docsUrl: `${cloudDocs}/docs/architecture.md`,
  },
  {
    id: 'registry',
    label: 'OCI Registry',
    eyebrow: 'Published artifacts',
    domain: 'infrastructure',
    position: [-10, 0.28, -10.9],
    visualKind: 'registry-rack',
    logoId: 'oci-registry',
    status: 'in-progress',
    gate: 'G0',
    summary: 'Authenticated, digest-only publication stores the complete remotely verified OCI graph.',
    owns: ['OCI manifests', 'Configs and layers', 'Digest-addressed release'],
    boundary:
      'Registry credentials are materialized per attempt and never enter build history or provenance.',
    docsUrl: `${cloudDocs}/docs/development-plan.md`,
  },
  {
    id: 'cpu-compute',
    label: 'CPU Compute',
    eyebrow: 'Host hardware',
    domain: 'infrastructure',
    position: [0, 0.28, -10.9],
    visualKind: 'cpu-array',
    logoId: 'cpu-compute',
    status: 'external',
    gate: 'Hardware',
    summary:
      'General-purpose CPU cores execute control helpers, build workers, services, and non-accelerated workloads.',
    owns: ['CPU cores', 'Host memory', 'Execution telemetry'],
    boundary: 'Cloud schedules typed Runtime intent; it never embeds hardware-specific lifecycle rules.',
    docsUrl: `${cloudDocs}/docs/architecture.md#3-universal-a3s-runtime-boundary`,
  },
  {
    id: 'gpu-compute',
    label: 'GPU Compute',
    eyebrow: 'Accelerator hardware',
    domain: 'infrastructure',
    position: [10, 0.28, -10.9],
    visualKind: 'gpu-array',
    logoId: 'gpu-compute',
    status: 'external',
    gate: 'I0 hardware',
    summary:
      'Advertised accelerator capabilities back typed inference plans and GPU-aware workload placement.',
    owns: ['GPU devices', 'Accelerator memory', 'Capability telemetry'],
    boundary:
      'Inference requests typed capabilities; Fleet and Runtime retain placement and execution authority.',
    docsUrl: `${cloudDocs}/docs/inference-plan.md`,
  },
] as const;

const ARCHITECTURE_EDGE_DEFINITIONS = [
  {
    id: 'clients-web',
    from: 'clients',
    to: 'web',
    label: 'operator intent',
    journeys: ['deploy', 'source', 'observe'],
  },
  {
    id: 'web-gateway',
    from: 'web',
    to: 'gateway',
    label: 'same-origin /api requests',
    journeys: ['deploy', 'source', 'observe'],
  },
  {
    id: 'code-gateway',
    from: 'code-tui',
    to: 'gateway',
    label: 'Cloud API commands',
    journeys: ['deploy', 'source', 'observe'],
  },
  {
    id: 'gateway-api',
    from: 'gateway',
    to: 'api',
    label: 'private /api upstream',
    journeys: ['deploy', 'source', 'observe'],
  },
  {
    id: 'github-sources',
    from: 'github',
    to: 'sources',
    label: 'signed event / exact revision',
    journeys: ['source'],
  },
  {
    id: 'api-identity',
    from: 'api',
    to: 'identity',
    label: 'authorize',
    journeys: ['deploy', 'source', 'observe'],
  },
  {
    id: 'api-projects',
    from: 'api',
    to: 'projects',
    label: 'scope',
    journeys: ['deploy', 'source'],
  },
  {
    id: 'api-workloads',
    from: 'api',
    to: 'workloads',
    label: 'desired revision',
    journeys: ['deploy'],
  },
  {
    id: 'api-sources',
    from: 'api',
    to: 'sources',
    label: 'source intent',
    journeys: ['source'],
  },
  {
    id: 'api-inference',
    from: 'api',
    to: 'inference',
    label: 'typed inference intent',
    journeys: ['deploy'],
  },
  {
    id: 'api-workflow',
    from: 'api',
    to: 'workflow',
    label: 'authorized goal / definition',
    journeys: ['deploy'],
  },
  {
    id: 'api-agents',
    from: 'api',
    to: 'agents',
    label: 'Agent intent / query',
    journeys: ['deploy', 'observe'],
  },
  {
    id: 'api-evolution',
    from: 'api',
    to: 'evolution',
    label: 'authorized evaluation intent',
    journeys: ['deploy', 'observe'],
  },
  {
    id: 'inference-power',
    from: 'inference',
    to: 'power',
    label: 'typed Power backend revision',
    journeys: ['deploy'],
  },
  {
    id: 'sources-artifacts',
    from: 'sources',
    to: 'artifacts',
    label: 'immutable build input',
    journeys: ['source'],
  },
  {
    id: 'artifacts-operations',
    from: 'artifacts',
    to: 'operations',
    label: 'BuildRun operation',
    journeys: ['source'],
  },
  {
    id: 'workloads-operations',
    from: 'workloads',
    to: 'operations',
    label: 'deployment operation',
    journeys: ['deploy'],
  },
  {
    id: 'workflow-operations',
    from: 'workflow',
    to: 'operations',
    label: 'one durable run',
    journeys: ['deploy'],
  },
  {
    id: 'workflow-agents',
    from: 'workflow',
    to: 'agents',
    label: 'typed Agent step',
    journeys: ['deploy'],
  },
  {
    id: 'agents-workloads',
    from: 'agents',
    to: 'workloads',
    label: 'immutable provider workload',
    journeys: ['deploy'],
  },
  {
    id: 'evolution-operations',
    from: 'evolution',
    to: 'operations',
    label: 'evaluation / candidate job',
    journeys: ['deploy'],
  },
  {
    id: 'operations-flow',
    from: 'operations',
    to: 'flow',
    label: 'durable workflow',
    journeys: ['deploy', 'source'],
  },
  {
    id: 'flow-node-agent',
    from: 'flow',
    to: 'node-agent',
    label: 'leased command',
    journeys: ['deploy', 'source'],
  },
  {
    id: 'node-runtime',
    from: 'node-agent',
    to: 'runtime',
    label: 'apply / remove',
    journeys: ['deploy', 'source'],
  },
  {
    id: 'runtime-box',
    from: 'runtime',
    to: 'box-provider',
    label: 'sole Box provider contract',
    journeys: ['deploy', 'source'],
  },
  {
    id: 'box-workload',
    from: 'box-provider',
    to: 'workload-unit',
    label: 'isolated OCI lifecycle',
    journeys: ['deploy'],
  },
  {
    id: 'box-cpu',
    from: 'box-provider',
    to: 'cpu-compute',
    label: 'CPU execution & build',
    journeys: ['deploy', 'source'],
  },
  {
    id: 'box-gpu',
    from: 'box-provider',
    to: 'gpu-compute',
    label: 'planned GPU binding',
    journeys: ['deploy'],
  },
  {
    id: 'power-cpu',
    from: 'power',
    to: 'cpu-compute',
    label: 'TEE CPU inference',
    journeys: ['deploy', 'observe'],
  },
  {
    id: 'power-gpu',
    from: 'power',
    to: 'gpu-compute',
    label: 'attested GPU inference',
    journeys: ['deploy', 'observe'],
  },
  {
    id: 'box-build-registry',
    from: 'box-provider',
    to: 'registry',
    label: 'validated OCI graph',
    journeys: ['source'],
  },
  {
    id: 'registry-workloads',
    from: 'registry',
    to: 'workloads',
    label: 'digest-only handoff',
    journeys: ['source'],
  },
  {
    id: 'runtime-workload',
    from: 'runtime',
    to: 'workload-unit',
    label: 'converged unit',
    journeys: ['deploy'],
  },
  {
    id: 'cpu-workload',
    from: 'cpu-compute',
    to: 'workload-unit',
    label: 'CPU health & output',
    journeys: ['deploy', 'traffic', 'observe'],
  },
  {
    id: 'gpu-workload',
    from: 'gpu-compute',
    to: 'workload-unit',
    label: 'GPU health & output',
    journeys: ['deploy', 'traffic', 'observe'],
  },
  {
    id: 'workload-edge',
    from: 'workload-unit',
    to: 'edge',
    label: 'healthy exact target',
    journeys: ['deploy'],
  },
  {
    id: 'edge-agent',
    from: 'edge',
    to: 'node-agent',
    label: 'complete snapshot',
    journeys: ['deploy'],
  },
  {
    id: 'agent-gateway',
    from: 'node-agent',
    to: 'gateway',
    label: 'apply & acknowledge',
    journeys: ['deploy'],
  },
  {
    id: 'clients-gateway',
    from: 'clients',
    to: 'gateway',
    label: 'HTTPS / streaming',
    journeys: ['traffic'],
  },
  {
    id: 'gateway-workload',
    from: 'gateway',
    to: 'workload-unit',
    label: 'healthy upstream',
    journeys: ['traffic'],
  },
  {
    id: 'workload-agent-logs',
    from: 'workload-unit',
    to: 'node-agent',
    label: 'ordered stdout / stderr',
    journeys: ['observe'],
  },
  {
    id: 'agent-fleet',
    from: 'node-agent',
    to: 'fleet',
    label: 'observation / cursor',
    journeys: ['observe'],
  },
  {
    id: 'fleet-object-store',
    from: 'fleet',
    to: 'object-storage',
    label: 'verified log chunks',
    journeys: ['observe'],
  },
  {
    id: 'object-store-api',
    from: 'object-storage',
    to: 'api',
    label: 'bounded log page',
    journeys: ['observe'],
  },
  {
    id: 'contexts-postgres',
    from: 'workloads',
    to: 'postgres',
    label: 'desired state',
    journeys: ['deploy', 'observe'],
  },
  {
    id: 'artifacts-store',
    from: 'artifacts',
    to: 'object-storage',
    label: 'command-bound archive',
    journeys: ['source'],
  },
  {
    id: 'contexts-event',
    from: 'projects',
    to: 'event',
    label: 'committed fact',
    journeys: ['deploy', 'source'],
  },
  {
    id: 'inference-workloads',
    from: 'inference',
    to: 'workloads',
    label: 'typed execution plan',
    journeys: ['deploy'],
  },
  {
    id: 'inference-fleet',
    from: 'inference',
    to: 'fleet',
    label: 'accelerator claims',
    journeys: ['deploy'],
  },
  {
    id: 'fleet-gpu',
    from: 'fleet',
    to: 'gpu-compute',
    label: 'capability lease & observation',
    journeys: ['deploy', 'observe'],
  },
  {
    id: 'inference-edge',
    from: 'inference',
    to: 'edge',
    label: 'model route policy',
    journeys: ['deploy'],
  },
] as const;

export const ARCHITECTURE_EDGES: readonly ArchitectureEdge[] = ARCHITECTURE_EDGE_DEFINITIONS.map((edge) => ({
  ...edge,
  ...architectureEdgeDetail(edge.id),
}));

export const JOURNEYS: readonly Journey[] = [
  {
    id: 'all',
    label: 'Complete system',
    shortLabel: 'All',
    description: 'Every current control, build, deployment, traffic, and observation relationship.',
    color: '#b8f36b',
  },
  {
    id: 'deploy',
    label: 'Deploy & converge',
    shortLabel: 'Deploy',
    description: 'From tenant intent to a healthy digest-pinned Runtime unit and acknowledged route.',
    color: '#b8f36b',
  },
  {
    id: 'source',
    label: 'Source to release',
    shortLabel: 'Build',
    description:
      'Exact Git revision, isolated A3S Box build, verified OCI publication, and Workload handoff.',
    color: '#f3c86b',
  },
  {
    id: 'traffic',
    label: 'Request data plane',
    shortLabel: 'Traffic',
    description: 'Clients reach only Gateway-selected healthy targets; Cloud stays off the request path.',
    color: '#72b7ff',
  },
  {
    id: 'observe',
    label: 'Logs & operations',
    shortLabel: 'Observe',
    description: 'Ordered provider output becomes verified objects, explicit gaps, and resumable UI state.',
    color: '#d7b6ff',
  },
] as const;

export const ARCHITECTURE_GRAPH: ArchitectureGraph = {
  domains: ARCHITECTURE_DOMAINS,
  nodes: ARCHITECTURE_NODES,
  edges: ARCHITECTURE_EDGES,
  journeys: JOURNEYS,
};

export function edgesForJourney(
  journey: JourneyId,
  edges: readonly ArchitectureEdge[] = ARCHITECTURE_EDGES
): readonly ArchitectureEdge[] {
  return journey === 'all' ? edges : edges.filter((edge) => edge.journeys.includes(journey));
}

export function nodeIdsForJourney(
  journey: JourneyId,
  edges: readonly ArchitectureEdge[] = ARCHITECTURE_EDGES
): ReadonlySet<string> {
  if (journey === 'all') {
    return new Set(ARCHITECTURE_NODES.map((node) => node.id));
  }
  const nodeIds = new Set<string>();
  for (const edge of edgesForJourney(journey, edges)) {
    nodeIds.add(edge.from);
    nodeIds.add(edge.to);
  }
  return nodeIds;
}
