#!/usr/bin/env bash
# Operator-owned U0.3 live Cloud↔host evidence collector (H57).
# Writes a validated LIVE_HOST_CERTIFIED line plus optional sidecars and a
# checklist. Never writes or prints A3S_CLOUD_U0_3_EXIT_CERTIFIED.
#
# Usage:
#   bash tools/use-conformance/collect_live_host_evidence.sh \
#     --host HOST --assignment ID --package ID --plan-digest DIGEST \
#     [--evidence-dir DIR] [optional sidecar flags...]
#
# Required fields may also come from env:
#   A3S_CLOUD_U0_3_LIVE_HOST, A3S_CLOUD_U0_3_LIVE_ASSIGNMENT,
#   A3S_CLOUD_U0_3_LIVE_PACKAGE, A3S_CLOUD_U0_3_LIVE_PLAN_DIGEST
# Optional evidence dir: A3S_CLOUD_U0_3_LIVE_EVIDENCE_DIR

set -euo pipefail

repository_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
tools="$repository_root/tools/use-conformance"
revision_file="$tools/use-revision"
validator="$tools/validate_live_host_certification.sh"

host=${A3S_CLOUD_U0_3_LIVE_HOST:-}
assignment=${A3S_CLOUD_U0_3_LIVE_ASSIGNMENT:-}
package=${A3S_CLOUD_U0_3_LIVE_PACKAGE:-}
plan_digest=${A3S_CLOUD_U0_3_LIVE_PLAN_DIGEST:-}
evidence_dir=${A3S_CLOUD_U0_3_LIVE_EVIDENCE_DIR:-}

operation_id=
flow_id=
plan_command_digest=
apply_command_digest=
observe_command_digest=
journal_plan_id=
journal_apply_id=
journal_observe_id=

usage() {
  cat <<'USAGE' >&2
usage: collect_live_host_evidence.sh --host HOST --assignment ID --package ID --plan-digest DIGEST [--evidence-dir DIR]
  optional: --operation-id --flow-id --plan-command-digest --apply-command-digest
            --observe-command-digest --journal-plan-id --journal-apply-id --journal-observe-id
USAGE
}

reject_placeholder() {
  local name=$1 value=$2
  if [[ -z $value ]]; then
    printf '%s\n' "required nonempty: $name" >&2
    exit 1
  fi
  if [[ $value == PLACEHOLDER_* ]]; then
    printf '%s\n' "refusing PLACEHOLDER_* for $name: $value" >&2
    exit 1
  fi
}

while (($# > 0)); do
  case $1 in
    --host)
      (($# >= 2)) || { usage; exit 1; }
      host=$2
      shift 2
      ;;
    --assignment)
      (($# >= 2)) || { usage; exit 1; }
      assignment=$2
      shift 2
      ;;
    --package)
      (($# >= 2)) || { usage; exit 1; }
      package=$2
      shift 2
      ;;
    --plan-digest)
      (($# >= 2)) || { usage; exit 1; }
      plan_digest=$2
      shift 2
      ;;
    --evidence-dir)
      (($# >= 2)) || { usage; exit 1; }
      evidence_dir=$2
      shift 2
      ;;
    --operation-id)
      (($# >= 2)) || { usage; exit 1; }
      operation_id=$2
      shift 2
      ;;
    --flow-id)
      (($# >= 2)) || { usage; exit 1; }
      flow_id=$2
      shift 2
      ;;
    --plan-command-digest)
      (($# >= 2)) || { usage; exit 1; }
      plan_command_digest=$2
      shift 2
      ;;
    --apply-command-digest)
      (($# >= 2)) || { usage; exit 1; }
      apply_command_digest=$2
      shift 2
      ;;
    --observe-command-digest)
      (($# >= 2)) || { usage; exit 1; }
      observe_command_digest=$2
      shift 2
      ;;
    --journal-plan-id)
      (($# >= 2)) || { usage; exit 1; }
      journal_plan_id=$2
      shift 2
      ;;
    --journal-apply-id)
      (($# >= 2)) || { usage; exit 1; }
      journal_apply_id=$2
      shift 2
      ;;
    --journal-observe-id)
      (($# >= 2)) || { usage; exit 1; }
      journal_observe_id=$2
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      printf '%s\n' "unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

reject_placeholder host "$host"
reject_placeholder assignment "$assignment"
reject_placeholder package "$package"
reject_placeholder plan_digest "$plan_digest"

if [[ ! -s $revision_file ]]; then
  printf '%s\n' "missing pinned revision: $revision_file" >&2
  exit 1
fi
revision=$(<"$revision_file")
revision=${revision//$'\n'/}
revision=${revision//$'\r'/}
if [[ ! $revision =~ ^[0-9a-f]{40}$ ]]; then
  printf '%s\n' "use-revision must be 40 lowercase hex: $revision" >&2
  exit 1
fi
if [[ $revision == PLACEHOLDER_* ]]; then
  printf '%s\n' "refusing PLACEHOLDER_* revision: $revision" >&2
  exit 1
fi

created_tmp=0
if [[ -z $evidence_dir ]]; then
  evidence_dir=$(mktemp -d "${TMPDIR:-/tmp}/a3s-cloud-u0-3-live-host-evidence.XXXXXX")
  created_tmp=1
else
  mkdir -p -- "$evidence_dir"
fi

cert_file="$evidence_dir/live-host-certification.txt"
cert_line="A3S_CLOUD_U0_3_LIVE_HOST_CERTIFIED revision=$revision host=$host assignment=$assignment package=$package plan_digest=$plan_digest"

# Guard: collector must never emit product EXIT_CERTIFIED.
if [[ $cert_line == *A3S_CLOUD_U0_3_EXIT_CERTIFIED* ]]; then
  printf '%s\n' "internal error: cert line must not contain EXIT_CERTIFIED" >&2
  exit 1
fi

{
  printf '%s\n' \
    "# Operator-collected U0.3 live Cloud↔host certification evidence." \
    "# Generated by tools/use-conformance/collect_live_host_evidence.sh" \
    "# revision pinned from tools/use-conformance/use-revision" \
    "$cert_line"
} >"$cert_file"

write_sidecar() {
  local name=$1 value=$2
  if [[ -n $value ]]; then
    if [[ $value == PLACEHOLDER_* ]]; then
      printf '%s\n' "refusing PLACEHOLDER_* for sidecar $name: $value" >&2
      exit 1
    fi
    printf '%s\n' "$value" >"$evidence_dir/$name"
  fi
}

write_sidecar operation-id "$operation_id"
write_sidecar flow-id "$flow_id"
write_sidecar plan-command-digest "$plan_command_digest"
write_sidecar apply-command-digest "$apply_command_digest"
write_sidecar observe-command-digest "$observe_command_digest"
write_sidecar journal-plan-id "$journal_plan_id"
write_sidecar journal-apply-id "$journal_apply_id"
write_sidecar journal-observe-id "$journal_observe_id"

provided_or_missing() {
  if [[ -n $1 ]]; then
    printf 'provided'
  else
    printf 'missing'
  fi
}

{
  printf '%s\n' \
    "U0.3 live-host operator evidence checklist" \
    "revision=$revision" \
    "host=$host" \
    "assignment=$assignment" \
    "package=$package" \
    "plan_digest=$plan_digest" \
    "" \
    "Required operator checklist items (retain outside this collector as needed):" \
    "- [ ] Cloud control-plane assignment Operation and Flow identity" \
    "- [ ] Fleet node_command delivery/ack digests for plan/apply/observe" \
    "- [ ] Node Agent journal replay of the same command IDs" \
    "- [ ] Real PluginHostManager observation converging desired/observed state" \
    "- [ ] No dual-version a3s-use embed in Cloud Cargo.toml" \
    "" \
    "Optional sidecar fields written by this collector:" \
    "- operation-id: $(provided_or_missing "$operation_id")" \
    "- flow-id: $(provided_or_missing "$flow_id")" \
    "- plan-command-digest: $(provided_or_missing "$plan_command_digest")" \
    "- apply-command-digest: $(provided_or_missing "$apply_command_digest")" \
    "- observe-command-digest: $(provided_or_missing "$observe_command_digest")" \
    "- journal-plan-id: $(provided_or_missing "$journal_plan_id")" \
    "- journal-apply-id: $(provided_or_missing "$journal_apply_id")" \
    "- journal-observe-id: $(provided_or_missing "$journal_observe_id")"
} >"$evidence_dir/checklist.txt"

bash "$validator" "$cert_file" "$revision"

if grep -R --fixed-strings --quiet 'A3S_CLOUD_U0_3_EXIT_CERTIFIED' "$evidence_dir" 2>/dev/null; then
  printf '%s\n' "collector must never write A3S_CLOUD_U0_3_EXIT_CERTIFIED under $evidence_dir" >&2
  exit 1
fi

printf '%s\n' \
  "live-host certification written: $cert_file" \
  "evidence directory: $evidence_dir" \
  "run exit audit with:" \
  "A3S_CLOUD_U0_3_LIVE_HOST_CERTIFICATION=$cert_file bash tools/use-conformance/run_u0_3_exit_audit.sh $evidence_dir"

if ((created_tmp == 1)); then
  printf '%s\n' "(evidence directory was created with mktemp; copy it if you need to retain it)"
fi
