#!/usr/bin/env bash
# Bootstrap first Organization / Project / Environment after live prep.
#
# Requires stack.env from run_bx0_software_exit_live_prep.sh (URL + bootstrap token).
# Never claims LOOP/EXIT. Never invents OCI digests.
#
# Usage:
#   source .a3s/cloud/bx0-live-prep/stack.env
#   bash tools/box-conformance/run_bx0_software_exit_live_tenant.sh [EVIDENCE_DIR]

set -euo pipefail

repository_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
tools="$repository_root/tools/box-conformance"

evidence_directory=${1:-}
if [[ -z $evidence_directory ]]; then
  evidence_directory=$(mktemp -d "${TMPDIR:-/tmp}/a3s-cloud-bx0-live-tenant.XXXXXX")
fi
mkdir -p -- "$evidence_directory"

fail_blocked() {
  local reason=$1
  shift || true
  cat <<EOF | tee "$evidence_directory/bx0-software-exit-live-tenant.txt"
A3S_CLOUD_BX0_SOFTWARE_EXIT_LIVE_TENANT_BLOCKED reason=$reason
$*
product_exit=not_claimed
loop_certified=not_claimed
EOF
  exit 2
}

# shellcheck disable=SC1090
source "$tools/bx0_refuse_docker_host.sh"
bx0_refuse_docker_host

api_url=${A3S_CLOUD_URL:-}
bootstrap_token=${A3S_CLOUD_BOOTSTRAP_TOKEN:-}
if [[ -z $api_url || $api_url == PLACEHOLDER_* ]]; then
  fail_blocked api_url_missing "hint=source live-prep stack.env first"
fi
if [[ -z $bootstrap_token || $bootstrap_token == PLACEHOLDER_* ]]; then
  fail_blocked bootstrap_token_missing
fi
if ! command -v curl >/dev/null 2>&1; then
  fail_blocked curl_unavailable
fi
if ! command -v bun >/dev/null 2>&1 && [[ -x ${HOME:-}/.bun/bin/bun ]]; then
  PATH="${HOME}/.bun/bin:$PATH"
fi
# Prefer a Linux-native bun; the Windows npm shim under /mnt/c does not inherit WSL env.
bun_bin=${A3S_CLOUD_BUN_BIN:-}
if [[ -z $bun_bin ]]; then
  if [[ -x ${HOME:-}/.bun/bin/bun ]]; then
    bun_bin="${HOME}/.bun/bin/bun"
  else
    bun_bin=$(command -v bun || true)
  fi
fi
if [[ -z $bun_bin || ! -x $bun_bin ]]; then
  fail_blocked bun_unavailable
fi
# Reject the Windows npm bun shim (breaks A3S_CLOUD_TOKEN inheritance on WSL).
if [[ $bun_bin == /mnt/c/* || $bun_bin == /mnt/d/Users/* ]]; then
  fail_blocked bun_windows_shim "path=$bun_bin hint=install Linux bun (curl -fsSL https://bun.sh/install | bash)"
fi
if ! command -v openssl >/dev/null 2>&1; then
  fail_blocked openssl_unavailable
fi
if ! command -v python3 >/dev/null 2>&1; then
  fail_blocked python3_unavailable
fi

org_name=${A3S_CLOUD_BX0_ORG_NAME:-bx0-software}
project_name=${A3S_CLOUD_BX0_PROJECT_NAME:-bx0-live}
environment_name=${A3S_CLOUD_BX0_ENVIRONMENT_NAME:-default}
prep_state=${A3S_CLOUD_BX0_LIVE_PREP_STATE_DIR:-$repository_root/.a3s/cloud/bx0-live-prep}
durable_tenant_env=${A3S_CLOUD_BX0_DURABLE_TENANT_ENV:-$prep_state/tenant.env}
idem_bootstrap=${A3S_CLOUD_BX0_BOOTSTRAP_IDEMPOTENCY_KEY:-bx0-live-tenant-bootstrap}

cloud_cli() {
  (
    cd -- "$repository_root/cli"
    "$bun_bin" src/main.ts --output=json "$@"
  )
}

write_tenant_env() {
  local out=$1
  {
    printf '# Generated by run_bx0_software_exit_live_tenant.sh\n'
    printf 'export A3S_CLOUD_URL=%q\n' "$A3S_CLOUD_URL"
    printf 'export A3S_CLOUD_TOKEN=%q\n' "$A3S_CLOUD_TOKEN"
    printf 'export A3S_CLOUD_ORGANIZATION_ID=%q\n' "$A3S_CLOUD_ORGANIZATION_ID"
    printf 'export A3S_CLOUD_PROJECT_ID=%q\n' "$A3S_CLOUD_PROJECT_ID"
    printf 'export A3S_CLOUD_ENVIRONMENT_ID=%q\n' "$A3S_CLOUD_ENVIRONMENT_ID"
  } >"$out"
  mkdir -p -- "$prep_state"
  cp -f -- "$out" "$durable_tenant_env"
}

finish_tenant_ok() {
  local reused=${1:-0}
  local tenant_env=${A3S_CLOUD_BX0_TENANT_OUT:-$evidence_directory/bx0-live-tenant-env.sh}
  write_tenant_env "$tenant_env"
  if [[ -f $prep_state/stack.env ]]; then
    {
      printf '\n# tenant (from run_bx0_software_exit_live_tenant.sh)\n'
      printf 'export A3S_CLOUD_TOKEN=%q\n' "$A3S_CLOUD_TOKEN"
      printf 'export A3S_CLOUD_ORGANIZATION_ID=%q\n' "$A3S_CLOUD_ORGANIZATION_ID"
      printf 'export A3S_CLOUD_PROJECT_ID=%q\n' "$A3S_CLOUD_PROJECT_ID"
      printf 'export A3S_CLOUD_ENVIRONMENT_ID=%q\n' "$A3S_CLOUD_ENVIRONMENT_ID"
    } >>"$prep_state/stack.env"
  fi
  cat <<EOF | tee "$evidence_directory/bx0-software-exit-live-tenant.txt"
A3S_CLOUD_BX0_SOFTWARE_EXIT_LIVE_TENANT_OK
organization_id=$A3S_CLOUD_ORGANIZATION_ID
project_id=$A3S_CLOUD_PROJECT_ID
environment_id=$A3S_CLOUD_ENVIRONMENT_ID
tenant_env=$tenant_env
durable_tenant_env=$durable_tenant_env
reused_durable_tenant=$reused
product_exit=not_claimed
loop_certified=not_claimed
honesty=Bootstrap + project/environment only; OCI/HEALTH/HTTPS still required for EXIT.
EOF
  exit 0
}

# Fast path: durable tenant identities still authenticate.
if [[ -f $durable_tenant_env ]]; then
  # shellcheck disable=SC1090
  source "$durable_tenant_env"
  if [[ -n ${A3S_CLOUD_TOKEN:-} && -n ${A3S_CLOUD_ORGANIZATION_ID:-} && -n ${A3S_CLOUD_PROJECT_ID:-} && -n ${A3S_CLOUD_ENVIRONMENT_ID:-} ]]; then
    export A3S_CLOUD_URL=$api_url
    set +e
    orgs_json=$(cloud_cli organizations list 2>"$evidence_directory/orgs-list.err")
    orgs_rc=$?
    set -e
    printf '%s\n' "$orgs_json" >"$evidence_directory/orgs-list.json"
    if ((orgs_rc == 0)); then
      finish_tenant_ok 1
    fi
  fi
fi

# Reuse durable admin token so bootstrap idempotency can replay across LIVE re-runs.
admin_token=${A3S_CLOUD_TOKEN:-}
if [[ -z $admin_token && -f $durable_tenant_env ]]; then
  # shellcheck disable=SC1090
  source "$durable_tenant_env"
  admin_token=${A3S_CLOUD_TOKEN:-}
fi
if [[ -z $admin_token ]]; then
  admin_token="a3s_$(openssl rand -hex 32)"
fi

# Strip trailing /api/v1 for bootstrap path construction
base=${api_url%/api/v1}
base=${base%/}
bootstrap_url="${base}/api/v1/bootstrap"

set +e
bootstrap_http=$(
  curl -sS --max-time 30 \
    --request POST "$bootstrap_url" \
    --header 'content-type: application/json' \
    --header "idempotency-key: $idem_bootstrap" \
    --header "x-a3s-bootstrap-token: $bootstrap_token" \
    --data "{\"organizationName\":\"${org_name}\",\"tokenName\":\"bx0-live-admin\",\"token\":\"${admin_token}\",\"expiresAt\":null}" \
    -w '\n%{http_code}'
)
bootstrap_curl_rc=$?
set -e
bootstrap_code=$(printf '%s\n' "$bootstrap_http" | tail -n1)
bootstrap_body=$(printf '%s\n' "$bootstrap_http" | sed '$d')
printf '%s\n' "$bootstrap_body" >"$evidence_directory/bootstrap.json"
printf 'http_code=%s\n' "$bootstrap_code" >"$evidence_directory/bootstrap.status"

organization_id=
replayed=0
if ((bootstrap_curl_rc != 0)); then
  fail_blocked bootstrap_http_failed "exit=$bootstrap_curl_rc url=$bootstrap_url"
fi

if [[ $bootstrap_code == 200 || $bootstrap_code == 201 ]]; then
  organization_id=$(
    python3 - "$bootstrap_body" <<'PY'
import json, sys
body = json.loads(sys.argv[1])
data = body.get("data") or body
org = data.get("organization") or {}
oid = org.get("id")
if not oid:
    raise SystemExit(1)
print(oid)
token = data.get("apiToken") or {}
if token.get("replayed") is True:
    print("REPLAYED", file=sys.stderr)
PY
  ) || fail_blocked bootstrap_parse_organization_id
  if python3 - "$bootstrap_body" <<'PY'
import json, sys
body = json.loads(sys.argv[1])
data = body.get("data") or body
token = data.get("apiToken") or {}
raise SystemExit(0 if token.get("replayed") is True else 1)
PY
  then
    replayed=1
  fi
elif [[ $bootstrap_code == 409 ]]; then
  if [[ -f $durable_tenant_env ]]; then
    # shellcheck disable=SC1090
    source "$durable_tenant_env"
  fi
  organization_id=${A3S_CLOUD_ORGANIZATION_ID:-}
  if [[ -z $organization_id || -z ${A3S_CLOUD_TOKEN:-} ]]; then
    fail_blocked bootstrap_already_done_without_tenant_env \
      "hint=source durable tenant.env or compose down/up for a fresh Postgres guest"
  fi
  admin_token=$A3S_CLOUD_TOKEN
  replayed=1
else
  fail_blocked bootstrap_http_failed "http=$bootstrap_code url=$bootstrap_url"
fi

export A3S_CLOUD_URL=$api_url
export A3S_CLOUD_TOKEN=$admin_token
export A3S_CLOUD_ORGANIZATION_ID=$organization_id

# Idempotent replay / CONFLICT: reuse durable project+environment when present.
if ((replayed == 1)) && [[ -f $durable_tenant_env ]]; then
  # shellcheck disable=SC1090
  source "$durable_tenant_env"
  if [[ -n ${A3S_CLOUD_PROJECT_ID:-} && -n ${A3S_CLOUD_ENVIRONMENT_ID:-} && ${A3S_CLOUD_ORGANIZATION_ID:-} == "$organization_id" ]]; then
    export A3S_CLOUD_TOKEN=$admin_token
    export A3S_CLOUD_ORGANIZATION_ID=$organization_id
    export A3S_CLOUD_PROJECT_ID
    export A3S_CLOUD_ENVIRONMENT_ID
    set +e
    orgs_json=$(cloud_cli organizations list 2>"$evidence_directory/orgs-list.err")
    orgs_rc=$?
    set -e
    printf '%s\n' "$orgs_json" >"$evidence_directory/orgs-list.json"
    if ((orgs_rc == 0)); then
      finish_tenant_ok 1
    fi
  fi
fi

idem_project="bx0-live-project-$(openssl rand -hex 4)"
set +e
project_json=$(cloud_cli projects create "$project_name" --idempotency-key="$idem_project")
project_rc=$?
set -e
printf '%s\n' "$project_json" >"$evidence_directory/project.json"
if ((project_rc != 0)); then
  # Name conflict on replay: recover durable project id when available.
  if [[ -f $durable_tenant_env ]]; then
    # shellcheck disable=SC1090
    source "$durable_tenant_env"
  fi
  if [[ -n ${A3S_CLOUD_PROJECT_ID:-} && -n ${A3S_CLOUD_ENVIRONMENT_ID:-} ]]; then
    export A3S_CLOUD_PROJECT_ID
    export A3S_CLOUD_ENVIRONMENT_ID
    finish_tenant_ok 1
  fi
  fail_blocked projects_create_failed "exit=$project_rc"
fi
project_id=$(
  python3 - "$project_json" <<'PY'
import json, sys
row = json.loads(sys.argv[1])
for key in ("id",):
    if isinstance(row, dict) and row.get(key):
        print(row[key]); raise SystemExit(0)
proj = row.get("project") if isinstance(row, dict) else None
if isinstance(proj, dict) and proj.get("id"):
    print(proj["id"]); raise SystemExit(0)
data = row.get("data") if isinstance(row, dict) else None
if isinstance(data, dict):
    if data.get("id"):
        print(data["id"]); raise SystemExit(0)
    p = data.get("project") or {}
    if p.get("id"):
        print(p["id"]); raise SystemExit(0)
raise SystemExit(1)
PY
) || fail_blocked project_id_parse
export A3S_CLOUD_PROJECT_ID=$project_id

idem_env="bx0-live-env-$(openssl rand -hex 4)"
set +e
env_json=$(cloud_cli environments create "$environment_name" --idempotency-key="$idem_env")
env_rc=$?
set -e
printf '%s\n' "$env_json" >"$evidence_directory/environment.json"
if ((env_rc != 0)); then
  if [[ -n ${A3S_CLOUD_ENVIRONMENT_ID:-} ]]; then
    export A3S_CLOUD_ENVIRONMENT_ID
    finish_tenant_ok 1
  fi
  fail_blocked environments_create_failed "exit=$env_rc"
fi
environment_id=$(
  python3 - "$env_json" <<'PY'
import json, sys
row = json.loads(sys.argv[1])
if isinstance(row, dict) and row.get("id"):
    print(row["id"]); raise SystemExit(0)
env = row.get("environment") if isinstance(row, dict) else None
if isinstance(env, dict) and env.get("id"):
    print(env["id"]); raise SystemExit(0)
data = row.get("data") if isinstance(row, dict) else None
if isinstance(data, dict):
    if data.get("id"):
        print(data["id"]); raise SystemExit(0)
    e = data.get("environment") or {}
    if e.get("id"):
        print(e["id"]); raise SystemExit(0)
raise SystemExit(1)
PY
) || fail_blocked environment_id_parse
export A3S_CLOUD_ENVIRONMENT_ID=$environment_id

finish_tenant_ok 0
