pub mod agents;
pub mod artifacts;
pub mod assets;
pub mod audit;
pub mod edge;
pub mod executions;
pub mod fleet;
pub mod forms;
pub mod identity;
pub mod integration_events;
pub mod operations;
mod platform;
pub mod plugins;
pub mod projects;
pub mod search;
pub mod secrets;
pub mod shared_kernel;
pub mod sources;
pub mod workflow;
pub mod workloads;

pub use platform::PlatformModule;
