mod applications;
mod arguments;
mod artifacts;
mod audit;
mod catalog;
mod connectors;
mod developer_workflows;
mod dispatch;
mod durable_cells;
mod edge;
mod execution_templates;
mod files;
mod forms;
mod handler;
mod identity;
mod module;
mod nodes;
mod notifications;
mod ontology;
mod operations;
mod plugins;
mod projects;
mod protocol;
mod search;
mod security;
mod sources;
mod tool_result;
mod workflow;
mod workloads;

pub use module::ManagementMcpModule;

pub use a3s_cloud_contracts::MCP_PROTOCOL_VERSION as MANAGEMENT_MCP_PROTOCOL_VERSION;
