mod domain_name_pattern;
mod gateway_rollout_policy;
mod gateway_snapshot_runtime_settings;
mod mcp_service_profile_admission;
mod mcp_service_profile_projection_binding;
mod mcp_workload_revision_projection_binding;
mod route_hostname;
mod route_path;
mod route_port_name;
mod route_target;
mod upstream_endpoint;

pub use domain_name_pattern::DomainNamePattern;
pub use gateway_rollout_policy::{GatewayRolloutPolicy, MAX_GATEWAY_SCOPE_MEMBERS};
pub(crate) use gateway_snapshot_runtime_settings::GatewaySnapshotRuntimeSettings;
pub use mcp_service_profile_admission::EdgeMcpServiceProfileAdmission;
pub use mcp_service_profile_projection_binding::EdgeMcpServiceProfileProjectionBinding;
pub use mcp_workload_revision_projection_binding::EdgeMcpWorkloadRevisionProjectionBinding;
pub use route_hostname::RouteHostname;
pub use route_path::RoutePath;
pub use route_port_name::RoutePortName;
pub use route_target::RouteTarget;
pub use upstream_endpoint::UpstreamEndpoint;
