#!/usr/bin/env bash
# Start local a3s-cloud dependencies and the control-plane API in the background.
# Prefer a3s-box compose; fall back to Docker containers matching deploy/dev/compose.acl ports.
# Docker here is local middleware only (Postgres/NATS/registry), never the Runtime Unit provider.
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
state_dir="${A3S_CLOUD_DEV_STATE_DIR:-$repository_root/.a3s/cloud/dev}"
pid_file="$state_dir/control-plane.pid"
log_file="$state_dir/control-plane.log"
env_file="$state_dir/stack.env"
meta_file="$state_dir/stack.meta"
compose_acl="$repository_root/deploy/dev/compose.acl"

pg_user=${A3S_CLOUD_POSTGRES_USER:-a3s_cloud}
pg_password=${A3S_CLOUD_POSTGRES_PASSWORD:-a3s_cloud}
pg_db=${A3S_CLOUD_POSTGRES_DB:-a3s_cloud}
postgres_port=${A3S_CLOUD_POSTGRES_PORT:-54320}
serving_role=${A3S_CLOUD_POSTGRES_SERVING_ROLE:-a3s_cloud_serving}
serving_password=${A3S_CLOUD_POSTGRES_SERVING_PASSWORD:-a3s_cloud_serving}
nats_port=${A3S_CLOUD_NATS_PORT:-42220}
nats_monitor_port=${A3S_CLOUD_NATS_MONITOR_PORT:-8220}
registry_port=${A3S_CLOUD_REGISTRY_PORT:-50020}
api_port=${A3S_CLOUD_API_PORT:-8080}

# Digests match deploy/dev/compose.acl (keep in sync).
NATS_IMAGE=${A3S_CLOUD_NATS_IMAGE:-nats:2.11-alpine@sha256:e4bf19f15fd3218814a4e3c9e0064e1334bd8aa20d5984b9f1a0afd084f8cc00}
REGISTRY_IMAGE=${A3S_CLOUD_REGISTRY_IMAGE:-registry:2.8.3@sha256:a3d8aaa63ed8681a604f1dea0aa03f100d5895b6a58ace528858a7b332415373}
POSTGRES_IMAGE=${A3S_CLOUD_POSTGRES_IMAGE:-postgres:17-alpine@sha256:742f40ea20b9ff2ff31db5458d127452988a2164df9e17441e191f3b72252193}

usage() {
  printf '%s\n' \
    'Usage: tools/dev/cloud_up.sh' \
    '' \
    'Bring up local Cloud dependencies and start the control-plane API (detached).' \
    'State: .a3s/cloud/dev/ (pid, log, stack.env). Stop with tools/dev/cloud_down.sh.'
}

case "${1:-}" in
  '') ;;
  --help | -h)
    usage
    exit 0
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac

require_command() {
  local command_name="$1"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    printf 'required command is unavailable: %s\n' "$command_name" >&2
    exit 1
  fi
}

port_open() {
  local host=$1
  local port=$2
  if command -v nc >/dev/null 2>&1; then
    nc -z "$host" "$port" >/dev/null 2>&1
    return $?
  fi
  (echo >/dev/tcp/"$host"/"$port") >/dev/null 2>&1
}

require_safe_pg_token() {
  local name=$1
  local value=$2
  if [[ ! $value =~ ^[A-Za-z0-9_]+$ ]]; then
    printf '%s must be alphanumeric/underscore: %s\n' "$name" "$value" >&2
    exit 1
  fi
}

write_env() {
  umask 077
  cat >"$env_file" <<EOF
# Generated by tools/dev/cloud_up.sh — do not commit
export A3S_CLOUD_POSTGRES_URL='$postgres_url'
export A3S_CLOUD_POSTGRES_MIGRATION_URL='$migration_postgres_url'
export A3S_CLOUD_BOOTSTRAP_TOKEN='$bootstrap_token'
export A3S_CLOUD_GITHUB_WEBHOOK_SECRET='$webhook_secret'
EOF
}

write_meta() {
  umask 077
  cat >"$meta_file" <<EOF
mode=$deps_mode
owned_containers=$owned_containers
started_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
}

api_running() {
  if [[ -f $pid_file ]]; then
    local pid
    pid=$(cat "$pid_file" 2>/dev/null || true)
    if [[ -n $pid ]] && kill -0 "$pid" 2>/dev/null; then
      return 0
    fi
  fi
  return 1
}

docker_psql() {
  local database=${1:-postgres}
  shift
  docker exec -i "$pg_admin_container" \
    psql -U "$pg_admin_user" -d "$database" -v ON_ERROR_STOP=1 "$@"
}

ensure_postgres_roles() {
  require_safe_pg_token serving_role "$serving_role"
  require_safe_pg_token serving_password "$serving_password"
  require_safe_pg_token pg_user "$pg_user"
  require_safe_pg_token pg_password "$pg_password"
  require_safe_pg_token pg_db "$pg_db"

  if [[ -z ${pg_admin_container:-} ]]; then
    if [[ -n ${operator_supplied_postgres:-} ]]; then
      printf 'skipping role bootstrap (operator-supplied Postgres URL)\n'
      return 0
    fi
    if command -v psql >/dev/null 2>&1 && port_open 127.0.0.1 "$pg_listen_port"; then
      printf 'bootstrapping Postgres roles via local psql on port %s\n' "$pg_listen_port"
      export PGPASSWORD=$pg_password
      if ! psql -h 127.0.0.1 -p "$pg_listen_port" -U "$pg_user" -d postgres -tAc \
        "SELECT 1 FROM pg_database WHERE datname='${pg_db}'" | grep -q 1; then
        psql -h 127.0.0.1 -p "$pg_listen_port" -U "$pg_user" -d postgres -v ON_ERROR_STOP=1 \
          -c "CREATE DATABASE ${pg_db}"
      fi
      psql -h 127.0.0.1 -p "$pg_listen_port" -U "$pg_user" -d postgres -v ON_ERROR_STOP=1 -c \
        "DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${serving_role}') THEN
    CREATE ROLE ${serving_role} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
      NOREPLICATION NOBYPASSRLS PASSWORD '${serving_password}';
  ELSE
    ALTER ROLE ${serving_role} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
      NOREPLICATION NOBYPASSRLS PASSWORD '${serving_password}';
  END IF;
END
\$\$;"
      psql -h 127.0.0.1 -p "$pg_listen_port" -U "$pg_user" -d postgres -v ON_ERROR_STOP=1 \
        -c "GRANT CONNECT ON DATABASE ${pg_db} TO ${serving_role}"
      unset PGPASSWORD
      migration_postgres_url="postgres://${pg_user}:${pg_password}@127.0.0.1:${pg_listen_port}/${pg_db}"
      postgres_url="postgres://${serving_role}:${serving_password}@127.0.0.1:${pg_listen_port}/${pg_db}"
      printf 'Postgres roles ready via psql: migration=%s serving=%s port=%s\n' \
        "$pg_user" "$serving_role" "$pg_listen_port"
      return 0
    fi
    printf '%s\n' \
      'cannot bootstrap a3s_cloud_serving: no docker Postgres admin container' \
      'Set A3S_CLOUD_POSTGRES_URL and A3S_CLOUD_POSTGRES_MIGRATION_URL, or start' \
      'a3s-cloud-dev-postgres / a3s-u03-pg so roles can be created.' >&2
    exit 1
  fi

  require_command docker
  printf 'bootstrapping Postgres database/roles on container %s\n' "$pg_admin_container"

  if ! docker_psql postgres -tAc \
    "SELECT 1 FROM pg_database WHERE datname='${pg_db}'" | grep -q 1; then
    docker_psql postgres -c "CREATE DATABASE ${pg_db}"
  fi

  if [[ $pg_admin_user != "$pg_user" ]]; then
    docker_psql postgres -c \
      "DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${pg_user}') THEN
    CREATE ROLE ${pg_user} LOGIN NOSUPERUSER CREATEDB CREATEROLE NOREPLICATION
      PASSWORD '${pg_password}';
  ELSE
    ALTER ROLE ${pg_user} WITH LOGIN NOSUPERUSER CREATEDB CREATEROLE NOREPLICATION
      PASSWORD '${pg_password}';
  END IF;
END
\$\$;"
    docker_psql postgres -c "ALTER DATABASE ${pg_db} OWNER TO ${pg_user}"
  fi

  docker_psql postgres -c \
    "DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${serving_role}') THEN
    CREATE ROLE ${serving_role} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
      NOREPLICATION NOBYPASSRLS PASSWORD '${serving_password}';
  ELSE
    ALTER ROLE ${serving_role} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
      NOREPLICATION NOBYPASSRLS PASSWORD '${serving_password}';
  END IF;
END
\$\$;"

  docker_psql postgres -c \
    "GRANT CONNECT ON DATABASE ${pg_db} TO ${serving_role}"

  migration_postgres_url="postgres://${pg_user}:${pg_password}@127.0.0.1:${pg_listen_port}/${pg_db}"
  postgres_url="postgres://${serving_role}:${serving_password}@127.0.0.1:${pg_listen_port}/${pg_db}"
  printf 'Postgres roles ready: migration=%s serving=%s port=%s\n' \
    "$pg_user" "$serving_role" "$pg_listen_port"
}

start_docker_container() {
  local name=$1
  shift
  if docker ps --format '{{.Names}}' | grep -qx "$name"; then
    return 0
  fi
  if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
    docker start "$name" >/dev/null
  else
    docker run -d --name "$name" "$@" >/dev/null
    if [[ -n ${owned_containers:-} ]]; then
      owned_containers="${owned_containers},${name}"
    else
      owned_containers="$name"
    fi
  fi
}

bring_up_deps() {
  pg_admin_container=
  pg_admin_user=
  pg_listen_port=$postgres_port
  owned_containers=
  operator_supplied_postgres=
  deps_mode=

  if [[ -n ${A3S_CLOUD_POSTGRES_URL:-} ]]; then
    deps_mode=existing-url
    operator_supplied_postgres=1
    postgres_url=$A3S_CLOUD_POSTGRES_URL
    migration_postgres_url=${A3S_CLOUD_POSTGRES_MIGRATION_URL:-$postgres_url}
    if [[ $postgres_url =~ @[^:]+:([0-9]+)/ ]]; then
      pg_listen_port=${BASH_REMATCH[1]}
    fi
    if command -v docker >/dev/null 2>&1; then
      if docker ps --format '{{.Names}}' | grep -qx 'a3s-cloud-dev-postgres'; then
        pg_admin_container=a3s-cloud-dev-postgres
        pg_admin_user=$pg_user
      elif docker ps --format '{{.Names}}' | grep -qx 'a3s-u03-pg'; then
        pg_admin_container=a3s-u03-pg
        pg_admin_user=postgres
      fi
    fi
    printf 'using existing A3S_CLOUD_POSTGRES_URL\n'
    return 0
  fi

  if command -v a3s-box >/dev/null 2>&1 && a3s-box info >/dev/null 2>&1; then
    deps_mode=a3s-box-compose
    a3s-box compose --file "$compose_acl" up --detach --timeout 120
    pg_listen_port=$postgres_port
    if command -v docker >/dev/null 2>&1 \
      && docker ps --format '{{.Names}}' | grep -qx 'a3s-cloud-dev-postgres'; then
      pg_admin_container=a3s-cloud-dev-postgres
      pg_admin_user=$pg_user
    fi
    # Temporary URLs until role bootstrap rewrites them.
    migration_postgres_url="postgres://${pg_user}:${pg_password}@127.0.0.1:${pg_listen_port}/${pg_db}"
    postgres_url=$migration_postgres_url
    printf 'dependencies via a3s-box compose\n'
    return 0
  fi

  require_command docker
  deps_mode=docker-fallback
  printf 'a3s-box unavailable; using Docker fallback for compose.acl ports\n'

  if ! docker image inspect "$POSTGRES_IMAGE" >/dev/null 2>&1 \
    && ! docker ps -a --format '{{.Names}}' | grep -qx 'a3s-cloud-dev-postgres' \
    && ! docker ps --format '{{.Names}}' | grep -qx 'a3s-u03-pg'; then
    printf 'image not present locally: %s\n' "$POSTGRES_IMAGE" >&2
    printf 'Pull it, or set A3S_CLOUD_POSTGRES_URL to an existing Postgres.\n' >&2
    exit 1
  fi

  if docker ps --format '{{.Names}}' | grep -qx 'a3s-u03-pg' \
    && ! docker ps --format '{{.Names}}' | grep -qx 'a3s-cloud-dev-postgres' \
    && ! port_open 127.0.0.1 "$postgres_port"; then
    # Reuse live-host prep Postgres when compose port is free but legacy is up.
    pg_listen_port=${A3S_CLOUD_LEGACY_PG_PORT:-54329}
    pg_admin_container=a3s-u03-pg
    pg_admin_user=postgres
    migration_postgres_url="postgres://${pg_user}:${pg_password}@127.0.0.1:${pg_listen_port}/${pg_db}"
    postgres_url=$migration_postgres_url
    printf 'reusing docker Postgres container a3s-u03-pg on port %s\n' "$pg_listen_port"
  else
    if ! docker image inspect "$POSTGRES_IMAGE" >/dev/null 2>&1 \
      && ! docker ps -a --format '{{.Names}}' | grep -qx 'a3s-cloud-dev-postgres'; then
      printf 'image not present locally: %s\n' "$POSTGRES_IMAGE" >&2
      exit 1
    fi
    start_docker_container a3s-cloud-dev-postgres \
      -e "POSTGRES_USER=$pg_user" \
      -e "POSTGRES_PASSWORD=$pg_password" \
      -e "POSTGRES_DB=$pg_db" \
      -p "${postgres_port}:5432" \
      "$POSTGRES_IMAGE"
    for _ in $(seq 1 60); do
      if docker exec a3s-cloud-dev-postgres pg_isready -U "$pg_user" -d "$pg_db" >/dev/null 2>&1; then
        break
      fi
      sleep 1
    done
    pg_listen_port=$postgres_port
    pg_admin_container=a3s-cloud-dev-postgres
    pg_admin_user=$pg_user
    migration_postgres_url="postgres://${pg_user}:${pg_password}@127.0.0.1:${pg_listen_port}/${pg_db}"
    postgres_url=$migration_postgres_url
  fi

  # NATS / registry are optional for memory events.provider; start when images exist.
  if docker image inspect "$NATS_IMAGE" >/dev/null 2>&1; then
    start_docker_container a3s-cloud-dev-nats \
      -p "${nats_port}:4222" -p "${nats_monitor_port}:8222" \
      "$NATS_IMAGE" \
      --jetstream --store_dir=/data --http_port=8222
  else
    printf 'WARNING: skipping NATS (image not local): %s\n' "$NATS_IMAGE" >&2
  fi
  if docker image inspect "$REGISTRY_IMAGE" >/dev/null 2>&1; then
    start_docker_container a3s-cloud-dev-registry \
      -p "${registry_port}:5000" \
      "$REGISTRY_IMAGE"
  else
    printf 'WARNING: skipping OCI registry (image not local): %s\n' "$REGISTRY_IMAGE" >&2
  fi
}

wait_for_api() {
  local deadline=$((SECONDS + 60))
  while ((SECONDS < deadline)); do
    if port_open 127.0.0.1 "$api_port"; then
      return 0
    fi
    if [[ -f $pid_file ]]; then
      local pid
      pid=$(cat "$pid_file")
      if ! kill -0 "$pid" 2>/dev/null; then
        printf 'control-plane exited early; see %s\n' "$log_file" >&2
        return 1
      fi
    fi
    sleep 0.5
  done
  printf 'timed out waiting for API on port %s; see %s\n' "$api_port" "$log_file" >&2
  return 1
}

mkdir -p "$state_dir"

if api_running; then
  printf 'a3s-cloud already running (pid %s)\n' "$(cat "$pid_file")"
  printf '  API: http://127.0.0.1:%s/api/v1\n' "$api_port"
  if [[ -f $env_file ]]; then
    # shellcheck disable=SC1090
    source "$env_file"
    if [[ -n ${A3S_CLOUD_BOOTSTRAP_TOKEN:-} ]]; then
      printf '  Bootstrap token: %s\n' "$A3S_CLOUD_BOOTSTRAP_TOKEN"
    else
      printf '  env: %s\n' "$env_file"
    fi
  fi
  exit 0
fi

require_command cargo
require_command openssl

bring_up_deps
ensure_postgres_roles

if [[ -z ${A3S_CLOUD_BOOTSTRAP_TOKEN:-} ]]; then
  bootstrap_token=$(openssl rand -hex 32)
else
  bootstrap_token=$A3S_CLOUD_BOOTSTRAP_TOKEN
fi
if [[ -z ${A3S_CLOUD_GITHUB_WEBHOOK_SECRET:-} ]]; then
  webhook_secret=$(openssl rand -hex 32)
else
  webhook_secret=$A3S_CLOUD_GITHUB_WEBHOOK_SECRET
fi

export A3S_CLOUD_POSTGRES_URL=$postgres_url
export A3S_CLOUD_POSTGRES_MIGRATION_URL=$migration_postgres_url
export A3S_CLOUD_BOOTSTRAP_TOKEN=$bootstrap_token
export A3S_CLOUD_GITHUB_WEBHOOK_SECRET=$webhook_secret

write_env
write_meta

target_directory="${CARGO_TARGET_DIR:-$repository_root/target}"
if [[ $target_directory != /* ]]; then
  target_directory="$repository_root/$target_directory"
fi
skip_prepare=${A3S_CLOUD_DEV_TEST_SKIP_PREPARE:-false}
if [[ $skip_prepare != true ]]; then
  (cd "$repository_root" && cargo build --locked -p a3s-cloud-control-plane)
fi
api_bin="${A3S_CLOUD_DEV_API_BIN:-$target_directory/debug/a3s-cloud-control-plane}"
migration_bin="${A3S_CLOUD_DEV_MIGRATION_BIN:-$target_directory/debug/a3s-cloud-migrate}"

cd "$repository_root"
A3S_CLOUD_POSTGRES_MIGRATION_URL="$migration_postgres_url" \
  "$migration_bin" config/cloud.acl
unset A3S_CLOUD_POSTGRES_MIGRATION_URL

# Detach: keep env for child; log to state dir.
nohup env \
  A3S_CLOUD_POSTGRES_URL="$postgres_url" \
  A3S_CLOUD_BOOTSTRAP_TOKEN="$bootstrap_token" \
  A3S_CLOUD_GITHUB_WEBHOOK_SECRET="$webhook_secret" \
  "$api_bin" config/cloud.acl \
  >>"$log_file" 2>&1 &
echo $! >"$pid_file"

if ! wait_for_api; then
  exit 1
fi

printf '%s\n' \
  'a3s-cloud is up:' \
  "  API: http://127.0.0.1:${api_port}/api/v1" \
  "  pid: $(cat "$pid_file")" \
  "  log: $log_file" \
  "  env: $env_file" \
  "  deps: $deps_mode" \
  "  Bootstrap token: $bootstrap_token"
