use a3s_orm::orm_table;
use chrono::{DateTime, Utc};
use uuid::Uuid;

orm_table! {
    pub(super) struct WorkloadRuntimeEvidenceHistory => "workload_runtime_evidence_history" {
        record_schema: String => "record_schema",
        binding_schema: String => "binding_schema",
        binding_id: Uuid => "binding_id",
        installation_id: Uuid => "installation_id",
        organization_id: Uuid => "organization_id",
        project_id: Uuid => "project_id",
        environment_id: Uuid => "environment_id",
        workload_id: Uuid => "workload_id",
        workload_revision_id: Uuid => "workload_revision_id",
        policy_id: Uuid => "policy_id",
        policy_revision_id: Uuid => "policy_revision_id",
        policy_revision_number: u64 => "policy_revision_number",
        policy_digest: String => "policy_digest",
        resource_claim_id: Uuid => "resource_claim_id",
        resource_claim_generation: u64 => "resource_claim_generation",
        resource_claim_aggregate_version: u64 => "resource_claim_aggregate_version",
        resource_claim_digest: String => "resource_claim_digest",
        resource_binding_digest: String => "resource_binding_digest",
        node_pool_id: Uuid => "node_pool_id",
        node_pool_aggregate_version: u64 => "node_pool_aggregate_version",
        node_pool_spec_digest: String => "node_pool_spec_digest",
        node_id: Uuid => "node_id",
        node_aggregate_version: u64 => "node_aggregate_version",
        agent_instance_id: Uuid => "agent_instance_id",
        node_capabilities_digest: String => "node_capabilities_digest",
        node_last_observed_at: DateTime<Utc> => "node_last_observed_at",
        runtime_report_id: Uuid => "runtime_report_id",
        runtime_unit_id: String => "runtime_unit_id",
        runtime_generation: u64 => "runtime_generation",
        runtime_class: String => "runtime_class",
        isolation_level: String => "isolation_level",
        semantics_profile_digest: String => "semantics_profile_digest",
        identity_attachment_digest: String => "identity_attachment_digest",
        runtime_spec_digest: String => "runtime_spec_digest",
        runtime_attestation_binding_digest: String => "runtime_attestation_binding_digest",
        provider_attestation_digest: String => "provider_attestation_digest",
        provider_resource_id: String => "provider_resource_id",
        provider_build: String => "provider_build",
        runtime_state: String => "runtime_state",
        runtime_observed_at: DateTime<Utc> => "runtime_observed_at",
        runtime_received_at: DateTime<Utc> => "runtime_received_at",
        node_attestation_binding_digest: Option<String> => "node_attestation_binding_digest",
        binding_digest: String => "binding_digest",
        admitted_at: DateTime<Utc> => "admitted_at",
    }
}
